Many bugfixes for xenserver puppet broker

diff --git a/files/puppet-xenserver.broker/install.erb b/files/puppet-xenserver.broker/install.erb
--- a/files/puppet-xenserver.broker/install.erb
+++ b/files/puppet-xenserver.broker/install.erb
@@ -103,9 +103,9 @@ esac
 
 # Log that the broker is finished.
 if cmd curl; then
-    curl -sL "<%= stage_done_url %>" || fail "curl failed to log broker completion"
+    curl -sL "<%= log_url("puppet installed", "info") %>" || fail "curl failed to log broker completion"
 elif cmd wget; then
-    wget -qO- "<%= stage_done_url %>" || fail "wget failed to log broker completion" &> /dev/null
+    wget -qO- "<%= log_url("puppet installed", "info") %>" || fail "wget failed to log broker completion" &> /dev/null
 else
     warn "neither curl nor wget installed; cannot log completion of broker"
 fi
